# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/plankton/CodeMax/LaserRangingV2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/plankton/CodeMax/LaserRangingV2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/plankton/CodeMax/LaserRangingV2/CMakeFiles /home/plankton/CodeMax/LaserRangingV2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/plankton/CodeMax/LaserRangingV2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LaserRanging

# Build rule for target.
LaserRanging: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LaserRanging
.PHONY : LaserRanging

# fast build rule for target.
LaserRanging/fast:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/build
.PHONY : LaserRanging/fast

algorithm.o: algorithm.cpp.o
.PHONY : algorithm.o

# target to build an object file
algorithm.cpp.o:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/algorithm.cpp.o
.PHONY : algorithm.cpp.o

algorithm.i: algorithm.cpp.i
.PHONY : algorithm.i

# target to preprocess a source file
algorithm.cpp.i:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/algorithm.cpp.i
.PHONY : algorithm.cpp.i

algorithm.s: algorithm.cpp.s
.PHONY : algorithm.s

# target to generate assembly for a file
algorithm.cpp.s:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/algorithm.cpp.s
.PHONY : algorithm.cpp.s

capture_frame.o: capture_frame.cpp.o
.PHONY : capture_frame.o

# target to build an object file
capture_frame.cpp.o:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/capture_frame.cpp.o
.PHONY : capture_frame.cpp.o

capture_frame.i: capture_frame.cpp.i
.PHONY : capture_frame.i

# target to preprocess a source file
capture_frame.cpp.i:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/capture_frame.cpp.i
.PHONY : capture_frame.cpp.i

capture_frame.s: capture_frame.cpp.s
.PHONY : capture_frame.s

# target to generate assembly for a file
capture_frame.cpp.s:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/capture_frame.cpp.s
.PHONY : capture_frame.cpp.s

image_processing.o: image_processing.cpp.o
.PHONY : image_processing.o

# target to build an object file
image_processing.cpp.o:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/image_processing.cpp.o
.PHONY : image_processing.cpp.o

image_processing.i: image_processing.cpp.i
.PHONY : image_processing.i

# target to preprocess a source file
image_processing.cpp.i:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/image_processing.cpp.i
.PHONY : image_processing.cpp.i

image_processing.s: image_processing.cpp.s
.PHONY : image_processing.s

# target to generate assembly for a file
image_processing.cpp.s:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/image_processing.cpp.s
.PHONY : image_processing.cpp.s

laser_ranging.o: laser_ranging.cpp.o
.PHONY : laser_ranging.o

# target to build an object file
laser_ranging.cpp.o:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/laser_ranging.cpp.o
.PHONY : laser_ranging.cpp.o

laser_ranging.i: laser_ranging.cpp.i
.PHONY : laser_ranging.i

# target to preprocess a source file
laser_ranging.cpp.i:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/laser_ranging.cpp.i
.PHONY : laser_ranging.cpp.i

laser_ranging.s: laser_ranging.cpp.s
.PHONY : laser_ranging.s

# target to generate assembly for a file
laser_ranging.cpp.s:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/laser_ranging.cpp.s
.PHONY : laser_ranging.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/main.cpp.s
.PHONY : main.cpp.s

timer.o: timer.cpp.o
.PHONY : timer.o

# target to build an object file
timer.cpp.o:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/timer.cpp.o
.PHONY : timer.cpp.o

timer.i: timer.cpp.i
.PHONY : timer.i

# target to preprocess a source file
timer.cpp.i:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/timer.cpp.i
.PHONY : timer.cpp.i

timer.s: timer.cpp.s
.PHONY : timer.s

# target to generate assembly for a file
timer.cpp.s:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/timer.cpp.s
.PHONY : timer.cpp.s

view_frame.o: view_frame.cpp.o
.PHONY : view_frame.o

# target to build an object file
view_frame.cpp.o:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/view_frame.cpp.o
.PHONY : view_frame.cpp.o

view_frame.i: view_frame.cpp.i
.PHONY : view_frame.i

# target to preprocess a source file
view_frame.cpp.i:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/view_frame.cpp.i
.PHONY : view_frame.cpp.i

view_frame.s: view_frame.cpp.s
.PHONY : view_frame.s

# target to generate assembly for a file
view_frame.cpp.s:
	$(MAKE) -f CMakeFiles/LaserRanging.dir/build.make CMakeFiles/LaserRanging.dir/view_frame.cpp.s
.PHONY : view_frame.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... LaserRanging"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... algorithm.o"
	@echo "... algorithm.i"
	@echo "... algorithm.s"
	@echo "... capture_frame.o"
	@echo "... capture_frame.i"
	@echo "... capture_frame.s"
	@echo "... image_processing.o"
	@echo "... image_processing.i"
	@echo "... image_processing.s"
	@echo "... laser_ranging.o"
	@echo "... laser_ranging.i"
	@echo "... laser_ranging.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... timer.o"
	@echo "... timer.i"
	@echo "... timer.s"
	@echo "... view_frame.o"
	@echo "... view_frame.i"
	@echo "... view_frame.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

